### ISSUE TITLE
Fiche mémo

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#21]
Pouvoir configurer pour chaque poste une fiche mémo, accessible à tous les utilisateurs (en fixe) et qui comprendrait les numéros de téléphones et infos utiles du poste.

**Comment by sapk** [comment]
Chaque équipe doit acceder à un mémo spécifique ou commune à tous le monde ?

**Comment by lcpdn** [comment]
Commune à tout le monde. :)

---

Loïc PEDEN
Élève ingénieur Télécom Bretagne
Apprenti ingénieur expert sécurité informatique
+33.(0).682.188.560
http://www.loicpeden.fr

Sauvez des arbres, mangez un bucheron et n'imprimez ce mail que si cela est
nécessaire.

2016-02-06 11:51 GMT+01:00 Antoine GIRARD notifications@github.com:

**Comment by titixbrest** [comment]
une fiche mémo pour tout le monde, éditable par un compte privilégié (le même que pour les ajout/suppression d'utilisateurs et de messages)
