### ISSUE TITLE
Empêcher l'affectation de fiche à des unités fantomes

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#24]
Il est possible actuellement d'affecter des fiches à une unité qui n'existe pas. Possible de l'empecher ou ça rentre en conflit avec le système offline ?

**Comment by sapk** [comment]
Non plus un problème de présentation des user par défaut couchdb ne permet pas à un user simple de voir les autres users. Les fonctions dans le code sont préparées pour le workflow mais necessite quelque changement dans les droits d'accès de la DB. De plus il serait plus simple si les utilisateurs pour avoir directement accès à la liste filtrabe par un champ de recherche.

**Comment by sapk** [comment]
Je sais pas si il faut bloquer le choix des identifiants (dans le cas ou le mobile est pas synchro et n'a pas la liste à jour) pour l'instant j'ai implémenté le fait d'afficher les équipes qui sont connus lors de l'affectation.

**Comment by titixbrest** [comment]
ca me va
