### ISSUE TITLE
Création de fiche "Express"

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#25]
Il serait intéressant de faire des fiches en mode express, pour pouvoir bénéficier d'un numéro de fiche, mais ne renseigner les éléments d'état-civil que plus tard. Par exemple dans le cas où la victime n'est pas immédiatement identifiable, pouvoir l'enregistrer immédiatement comme victime et compléter son identité plus tard.

**Comment by sapk** [comment]
En gros permettre de valider la création de la fiche sans que les infos soient saisie et permettre la modification de ces informations après ?

**Comment by sapk** [comment]
En gros permettre de valider la création de la fiche sans que l'info soit saisie et permettre la modification de ces informations après ?

**Comment by titixbrest** [comment]
Yes c'est ca

-------- Message d'origine --------
De : Antoine GIRARD notifications@github.com 
Date :07/02/2016  19:10  (GMT+01:00) 
A : adentes-org/SOFIA SOFIA@noreply.github.com 
Cc :  
Objet : Re: [SOFIA] Création de fiche "Express" (#25) 

En gros permettre de valider la création de la fiche sans que les infos soient saisie et permettre la modification de ces informations après ?

**Comment by sapk** [comment]
En gros permettre de valider la création de la fiche sans que l'info soit saisie et permettre la modification de ces informations après ?

**Comment by sapk** [comment]
Le commit 9a50a24399ab30dbc5439e669313efe5581e6960 permet de visualiser l'id dès la création de la fiche. il manque plus que l'édition des champs à postériorit.

**Comment by sapk** [comment]
Peut-être aussi afficher des mot de remplacement type "Iconnu(e)" à la place de l'info manquante dans la vue fiche.
