### ISSUE TITLE
Interface privilège

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#27]
Pouvoir bénéficier d'une interface utlisateur privilégié permettant la visualisation de toutes les fiches en cours et la suppression si nécessaire.

**Comment by sapk** [comment]
Solution idem à #26 ou il faut que cela soit dispo dans l'app aussi ?

**Comment by lcpdn** [comment]
Dans l'idée, il faudrait que la #26 soit accessible une fois AVANT le poste à un responsable départemental (par ex) et que pour la #27, ce soit accessible au chef de poste PENDANT le poste. Pas sûr que ce soit indispensable dans l'appli si t'as une interface Web qui le permet.

**Comment by titixbrest** [comment]
effectivement, l'interface web suffira pour toutes les tâches d'administration.

**Comment by sapk** [comment]
Done in app !
