### ISSUE TITLE
Enlever la popup de validation

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#28]
Laisser la possibilité d'enlever la popup de validation systématique à chaque étape.

**Comment by sapk** [comment]
On laisse le choix à l'utilisateur ou à l'admin ?

**Comment by titixbrest** [comment]
A l'utilisateur c'est pas mal ça :)

-------- Message d'origine --------
De : Antoine GIRARD notifications@github.com 
Date :07/02/2016  18:38  (GMT+01:00) 
A : adentes-org/SOFIA SOFIA@noreply.github.com 
Cc :  
Objet : Re: [SOFIA] Enlever la popup de validation (#28) 

On laisse le choix à l'utilisateur ou à l'admin ?

**Comment by sapk** [comment]
Done in 702c6673ed75631655ccbe94bf66155a13c08e3a
