### ISSUE TITLE
Bouton valider ne marche pas.

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#29]
Sur version Web et APK sur certains terminaux Android (Sony XPeria Aqua 4 par ex), le bouton Valider n'est pas fonctionnel.

**Comment by sapk** [comment]
Pour l'ajout de fiche ou pour tous les boutons valider?

**Comment by lcpdn** [comment]
Ca dépend des terminaux. Y en a c'est pour l'ajout d'une affection, d'autres pour le transfert d'une fiche, d'autres pour la validation de création, d'autres pour plusieurs...

**Comment by titixbrest** [comment]
pour ma part sur le dernier commit ca le fait aussi sur un chrome sur debian 8 (j'ai pas la version sous la main mais si vraiment ca peut aider je veux bien allumer mon virtualbox ^^)

**Comment by sapk** [comment]
Toujours d'actualité avec les changements ?

**Comment by lcpdn** [comment]
Je ne sais pas, mon téléphone n'était pas affecté. Le téléphone perso de @titixbrest l'était je crois.

**Comment by titixbrest** [comment]
pour etre franc, je ne sais plus de quoi ça parle . ...

**Comment by sapk** [comment]
On clôt et on voit si ça revient.
