### ISSUE TITLE
Retour au menu systématique pour ajout d'info

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#30]
Entre chaque ajout d'info, il semble nécessaire de revenir au menu pour que les modifs soient prises en compte, une par une (sur Samsung Galaxy S6 ou Tablette)

**Comment by sapk** [comment]
Dans le cadre d'un ajout d'information (affections, owner, .... ?) à une fiche ?

**Comment by lcpdn** [comment]
Oui. Sinon, t'es souvent dans le cas où tes modifs sont pas prises en compte.

**Comment by sapk** [comment]
Le cas que je voit possible est qu'un utilisateur qui recoit une fiche ne la voit pas poper sans rafraichissement sa liste de fiche qui lui est assigné. Je vais voir ce qu'il est possible de faire car je viens de mettre en place la base locale et elle peut décancher de évenement lorsqu'il ya des évenement sur la BDD distante

**Comment by lcpdn** [comment]
Résolu
