### ISSUE TITLE
Ajouter les traductions sur le panneau de configuration

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#46]
Sur les sliders et les boutons de déconnexion et de réinitialisation des paramètres

**Comment by sapk** [comment]
For ref : http://requirejs.org/docs/api.html#i18n

**Comment by sapk** [comment]
Fait pour cette partie et ajout du support de la traduction dans toute l'application avec du coup relecture du code pour unifier le language de programmation en anglais.
