### ISSUE TITLE
Bug sur galaxy S5

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#49]
traces chez Loic, simplement pour tracer le truc et ne pas l'oublier :D

**Comment by lcpdn** [comment]
@titixbrest : Un retour sur la persistance du bug après la correction ?

**Comment by titixbrest** [comment]
Bug toujours présent avec la derniere release
![screenshot_2016-04-21-09-13-15](https://cloud.githubusercontent.com/assets/3704701/14700677/7ae392f6-07a1-11e6-9685-eb746afe1fe3.png)

**Comment by sapk** [comment]
Ok bah faudrat que je test sinon une autre solution que je connaissait pas avant pour charger les template avec requirejs.

**Comment by sapk** [comment]
Est-ce que cette version de test résous le problème ? https://github.com/adentes-org/SOFIA/releases/tag/testing-bug-1

**Comment by titixbrest** [comment]
Il y a du mieux, l'ecran d'accueil est affiché.
Par contre pas possible d'afficher les parametres de connexion pour tester plus avant.
![screenshot_2016-04-24-14-59-14](https://cloud.githubusercontent.com/assets/3704701/14767733/66e9b260-0a2d-11e6-9252-d72179f5ebbc.png)
![screenshot_2016-04-24-14-58-56](https://cloud.githubusercontent.com/assets/3704701/14767735/71bbfa4a-0a2d-11e6-9181-2963916b9714.png)

**Comment by sapk** [comment]
@titixbrest Est-ce que https://github.com/adentes-org/SOFIA/releases/tag/testing-bug-5 peut corriger le nouveau bug ?

**Comment by titixbrest** [comment]
J'ai accès à la page de modification des paramètres de connexion, mais pas moyen de scanner le qrcode ni de pouvoir saisir a la main les paramètres. Les deux champs ne me donnent pas de clavier.

**Comment by sapk** [comment]
On avance ^^ 
Je crois que j'ai cassé des trucs  en voulant réduire la taille de l'apk mais que le dernier est bon je vais revoir avant si il fonctionne sur mon tel.

**Comment by sapk** [comment]
Cette version est ok sur mon téléphone pour la saisie par qrcode : https://github.com/adentes-org/SOFIA/releases/tag/testing-slim-dev3 à voir pourquoi le clavier n'apparait pas.

**Comment by sapk** [comment]
Est-ce qu'il saurait possible de tester d'installer https://play.google.com/store/apps/details?id=com.google.android.webview&hl=fr et après de relancer l'application ?

**Comment by sapk** [comment]
Si le problème persiste encore on pourra tester https://crosswalk-project.org/documentation/cordova.html qui ajoute le navigateur web avec l'app comme ça on élimine certaine dépendance sur les téléphones

**Comment by titixbrest** [comment]
Pour info il est encore dans la derniere release

**Comment by sapk** [comment]
:-(

**Comment by sapk** [comment]
Autre avantage de tester crosswalk est la possibilité de faire des applications "native" windows/linux.

https://crosswalk-project.org/documentation/windows/build_an_application.html
https://crosswalk-project.org/documentation/linux.html

**Comment by sapk** [comment]
Les versions (armv7,x86) avec crosswalk sont fonctionnelles (normalement) : https://github.com/adentes-org/SOFIA/releases/tag/test-crosswalk-8-bis

**Comment by sapk** [comment]
Lors d'un test avec firefox il semblerait que le problème soit identique

Message de warning dans firefox : Use of Mutation Events is deprecated. Use MutationObserver instead. (dans la librairie dialog-polyfill)

cf: https://github.com/GoogleChrome/dialog-polyfill/issues/103

**Comment by titixbrest** [comment]
Ca marche avec la version 1.0 beta 1 d'il y a 15 jours
