### ISSUE TITLE
feature request : Interface d'admin : gérer le page break sur un format A4 pour permettre l'impression des cartes de connexion avec les QR codes

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#51]
au passage, peut-etre réduire la taille des QR codes ?

**Comment by sapk** [comment]
Semble lié à chrome sous firefox ça donne cela comme résultat : [mozilla.pdf](https://github.com/adentes-org/SOFIA/files/189334/mozilla.pdf)

**Comment by sapk** [comment]
Après quelques tests je comprends pas ce que fait chrome lorsque je lui demande d'appliquer le style la page aurait à l'impression (print) j'ai la même chose que firefox comme rendu mais lorsque j'imprime c'est tous moche. A investiguer

**Comment by sapk** [comment]
https://github.com/adentes-org/sofia-admin-app/issues/1
