### ISSUE TITLE
Feature request : vue "Mes fiches" mise en évidence des mineurs

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#53]
Pour les victimes pour lesquelles une date de naissance est renseignée, effectuer le calcul de l'age et inscrire : 
- en orange les dates de naissance des victimes mineures dont l'age est > à 16 ans et < 18 ans
- en rouge les dates de naissance des victimes mineures dont l'age est <= à 16 ans
- en noir les autres dates de naissance

**Comment by sapk** [comment]
![capture d ecran_2016-04-01_14-43-14](https://cloud.githubusercontent.com/assets/4052400/14207098/1c6e8b74-f818-11e5-8d92-d33b4f18c3dc.png)
Du coup est-ce que je laisse la date de naissance affichée dans la vue fiche ou plutot l'année ?

**Comment by sapk** [comment]
Remarque y'a la place pour les deux.
