### ISSUE TITLE
feature request : ne pas pouvoir clore une fiche sans avoir saisie d'atteinte principale

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#56]

**Comment by sapk** [comment]
Normalement il devrait y avoir forcement une car la première qui est saisie est définit comme principale. Ou alors il y a un problème. Du coup c'est qu'il faut empêcher la fermeture si il n'y pas d'atteinte ? ou laors c'est que l'on doit demander la confirmation de l'atteinte principale ?

**Comment by titixbrest** [comment]
Sur panoramas, il y avait pas mal de fiches pour lesquelles il y avait aucune atteinte saisie.
N'étant pas sur place je ne sais pas quel user story mène à ça dsl...

Ce qu'il faut, c'est que tout le monde ait eu mal quelque part ^^. Je pensr que de reafficher le truc de selection de l'atteinte avant de fermer est pas mal.

Titi

-------- Message d'origine --------
De : Antoine GIRARD notifications@github.com 
Date :14/04/2016  13:15  (GMT+01:00) 
A : adentes-org/SOFIA SOFIA@noreply.github.com 
Cc : Thierry thierry.guibert@free.fr 
Objet : Re: [adentes-org/SOFIA] feature request : ne pas pouvoir clore une
  fiche sans avoir saisie d'atteinte principale (#56) 

Normalement il devrait y avoir forcement une car la première qui est saisie est définit comme principale. Ou alors il y a un problème. Du coup c'est qu'il faut empêcher la fermeture si il n'y pas d'atteinte ? ou laors c'est que l'on doit demander la confirmation de l'atteinte principale ?

**Comment by lcpdn** [comment]
Voir #62 pour une explication probable du bug de panorama. Ca doit être dû à un problème de synchro du client web.
