### ISSUE TITLE
bug : A analyser : possibilité de blocage sur l'écran d'accueil avec bloc de login non chargé. Nécessité d'un refresh pour avancer.

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#58]

**Comment by sapk** [comment]
C'est à dire que a certains moment au lancement tu te retrouves sur une page de login non réactive et que le refresh résouds ce problème ?

**Comment by titixbrest** [comment]
Yes 

-------- Message d'origine --------
De : Antoine GIRARD notifications@github.com 
Date :09/04/2016  19:54  (GMT+01:00) 
A : adentes-org/SOFIA SOFIA@noreply.github.com 
Cc : Thierry thierry.guibert@free.fr 
Objet : Re: [adentes-org/SOFIA] bug : A analyser : possibilité de blocage sur l'écran d'accueil avec bloc de login non chargé. Nécessité d'un refresh pour avancer. (#58) 

C'est à dire que a certains moment au lancement tu te retrouves sur une page de login non réactive et que le refresh résouds ce problème ?

**Comment by sapk** [comment]
Ceci a peut-être été fixé avec les réorganisations du chargement des dependances détecté en cherchant à corriger le bug sur S5.#49
