### ISSUE TITLE
Evol : changer le texte du bouton "Réinitialiser les identifiants" en "Se déconnecter"

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#59]

**Comment by sapk** [comment]
En faite je me suis longtemps posé la question est ce que lorsque l'on nettoye les identifiants en se déconnectant car de mon point de vue le seul cas où l'on voudrait se déconnecter serait lorsque l'on veut se connecter avec un autre compte. Donc en attendant, et pendant la phase de développement, j'ai préféré préciser mais effectivement ça correspond à se deconnecter.
