### ISSUE TITLE
Bug sur client web

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#62]
RetEx Petarades:

Après un certain délai après la connexion, le bandeau de la page passait en grisé. J'en ai déduit que le client était désynchro.
Si on tente de saisir une affection ou un mode d'admission, le client les affiche saisies, mais à la synchro suivante, les ajouts offlines sont discarded.
Solution de contournement "terrain": rafraichir (F5) la page après la saisie de l'état civil.
Deuxième solution terrain: saisir suffisament rapidement pour ne pas passer en offline

**Comment by sapk** [comment]
Les client avait un connexion stable ? c'est pour savoir si la deconnexion est lié au soft ou à la connexion et sinon pour le reste faut que je reproduise.

**Comment by sapk** [comment]
Et est-ce que tu sais si quelqu'un d'autre éditait la fiche en parallèle ?

**Comment by lcpdn** [comment]
La connexion était stable (PC fixe sur le réseau du CROUS il me semble)
Aucune édition en parallèle.

**Comment by titixbrest** [comment]
Alors : 
- réseau wifi stable
- Poste en mono utilisateur

**Comment by sapk** [comment]
Je me rappel d'avoir corriger un problème ou la libraire ne se reconnecte pas si elle est déconnecter (@d692861)-> à tester
