### ISSUE TITLE
Saisie des heures de bilan de surveillance 

### ISSUE THREAD

**Issue by lcpdn** [adentes-org/SOFIA#63]
Idée (à valider par @titixbrest) pouvoir enregistrer sur une fiche l'action "Bilan de surveillance effectué". 
Avec une fonctionnalité adjacente: Faire ressortir en couleur (orange/rouge) les fiches des victimes dans le PMA dont le dernier bilan de surveillance remonte à un délai supérieur à celui fixé.

**Comment by titixbrest** [comment]
Sur le plan opérationnel, vu du commandement c'est intéressant.
Maintenant sur les conditions logistiques de réalisation, c'est plus chaud.... 
Je dirais OK pour moi mais ne mettez pas toutes vos ressources vives là-dessus.

**Comment by sapk** [comment]
Cette action serait faisable du coup que par celui qui possède la fiche ?

**Comment by titixbrest** [comment]
Oui

Envoyé depuis mon smartphone Samsung Galaxy.

-------- Message d'origine --------
De : Antoine GIRARD notifications@github.com 
Date :02/06/2016  15:12  (GMT+01:00) 
A : adentes-org/SOFIA SOFIA@noreply.github.com 
Cc : Thierry thierry.guibert@free.fr, Mention mention@noreply.github.com 
Objet : Re: [adentes-org/SOFIA] Saisie des heures de bilan de surveillance 
  (#63) 

Cette action serait faisable du coup que par celui qui possède la fiche ?
