### ISSUE TITLE
Les données d'url de serveur de bdd et le nom de base de la conf ne sont plus prise en compte par défaut

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#70]
Sur develop.

**Comment by sapk** [comment]
C'est à dire qu'il reste bloqué sur une ancienne url ? Est-ce que le fait de nettoyer les données de l'application par l'interface d'Android résout le problème ? (dans ce cas là cela veut dire qu'il y'a un truc qui reste en cache quelque part)

**Comment by titixbrest** [comment]
Sur un déploiement tout neuf en mode web (sur un apache) les données du fichier de conf ne sont pas mises dans les champs adhoc

Envoyé depuis mon smartphone Samsung Galaxy.

-------- Message d'origine --------
De : Antoine GIRARD notifications@github.com 
Date :07/06/2016  14:17  (GMT+01:00) 
A : adentes-org/SOFIA SOFIA@noreply.github.com 
Cc : Thierry thierry.guibert@free.fr, Author author@noreply.github.com 
Objet : Re: [adentes-org/SOFIA] Les données d'url de serveur de bdd et le nom de base de la conf ne sont plus prise en compte par défaut (#70) 

C'est à dire qu'il reste bloqué sur une ancienne url ? Est-ce que le fait de nettoyer les données de l'application par l'interface d'Android résout le problème ? (dans ce cas là cela veut dire qu'il y'a un truc qui reste en cache quelque part)

**Comment by sapk** [comment]
De quel fichier de config tu parles ?

**Comment by titixbrest** [comment]
Dans assets/js/sofia.config.js (de tête)

Envoyé depuis mon smartphone Samsung Galaxy.

-------- Message d'origine --------
De : Antoine GIRARD notifications@github.com 
Date :07/06/2016  15:27  (GMT+01:00) 
A : adentes-org/SOFIA SOFIA@noreply.github.com 
Cc : Thierry thierry.guibert@free.fr, Author author@noreply.github.com 
Objet : Re: [adentes-org/SOFIA] Les données d'url de serveur de bdd et le nom de base de la conf ne sont plus prise en compte par défaut (#70) 

De quel fichier de config tu parles ?

**Comment by sapk** [comment]
Depuis quelques commit la fichiers js ne sont plus directement ceux dans assets mais ceux après nettoyage/minification avec la commande gulp et qui sont placé dans www/dist ils faut donc les regenerer avec la commande par défaut : gulp. Après il y a un deuxième conflit si on a déjà visité l'url il peut y avoir une ancienne configuration dans localstorage qui écrasera les paramètres par défaut.
