### ISSUE TITLE
Disparition de la barre de recherche de victime

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/SOFIA#93]
Sur l'interface web générée depuis la master, disparition de la barre de recherche en haut.

Elle apparait lorsque l'on visualise le site depuis un mobile. Pas testé avec une tab.

**Comment by sapk** [comment]
Ceci a été résolu dans #89 mais il y a pas eu de version de compilée.

**Comment by sapk** [comment]
J'ai relancé une version sur la branche master car il ya pas mal de correctif qui ont été appliqué depuis la beta1. 
Nouvelle version : https://github.com/adentes-org/SOFIA/releases/tag/v0.1.0-beta2

**Comment by sapk** [comment]
Par contre il semble que si on va sur une fiche et l'on revient l'icon n'est plus visible.

**Comment by sapk** [comment]
Devrait être corrigé dans https://github.com/adentes-org/SOFIA/releases/tag/v0.1.0-beta2.1
